export const thirdComponentStyles = {
    mainContainer: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      width: '100%',
      // minHeight: '100vh',
      padding: '20px 0',
      gap: 4,
    },
    titleSection: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      gap: 3,
      paddingTop: 2,
      paddingBottom: 2,
      width: '100%',
    },
    
    title: {
      fontSize: 25,
fontFamily: 'Lexend Deca',
fontWeight: '600',
      lineHeight: '20px',
      textAlign: 'center',
      color: '#111111',
      textTransform: 'uppercase',
    },
    subtitle: {
      fontSize: '15px',
      fontWeight: 400,
      lineHeight: '0px',
      textAlign: 'center',
      color: '#111111',
    },
    toolCard: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      width: 286,
      height: 313,
      padding: '42.5px 6px',
      borderRadius: 1,
      background: 'rgba(192, 150, 83, 0.20)',
      border: '1px solid rgba(192, 150, 83, 0.20)',
      gap: 4,
    },
    toolTitle: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      fontSize: '27px',
      fontWeight: 400,
      fontFamily: 'Butterscotch, sans-serif',
      color: '#C09653',
      '&::before, &::after': {
        content: '""',
        flexGrow: 1,
        height: '2px',
        background: '#C09653',
        margin: '0 10px',
      },
    },
    toolDescription: {
      fontSize: '15px',
      fontWeight: 600,
      lineHeight: '27px',
      textAlign: 'center',
      color: '#111111',
    },
    divider: {
        width: '53%',
        borderBottom: '2px solid #111111',
        marginBottom: '20px',
        marginTop: '20px',
        position: 'relative',
        '&::before, &::after': {
          content: '""',
          position: 'absolute',
          top: '-4px',
          width: '8px',
          height: '8px',
          borderRadius: '50%',
          backgroundColor: '#111111',
        },
        '&::before': {
          left: '0',
        },
        '&::after': {
          right: '0',
        }
      },
};
