import { SxProps, Theme } from "@mui/material";

export const reportToWosomStyles: { [key: string]: SxProps<Theme> } = {
  container: {
    width: "100%",
    height: "100%",
    position: "relative",
    background: "white",
  },
  formWrapper: {
    width: 547,
    padding: "35px 17px 40px 17px",
    margin: "0 auto",
    marginTop: "40px",
    marginBottom: "40px",
    position: "relative",
    background: "white",
    boxShadow: "0px 4px 18px rgba(0, 0, 0, 0.15)",
    borderRadius: "12px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "center",
  },
  header: {
    textAlign: "center",
    color: "#212121",
    fontSize: 25,
    fontFamily: "Lexend Deca",
    fontWeight: "600",
    lineHeight: "41.37px",
    letterSpacing: 1,
    wordWrap: "break-word",
    marginBottom: "15px",
  },
  subHeader: {
    textAlign: "center",
    color: "#A9A9A9",
    fontSize: 15,
    fontFamily: "Lexend Deca",
    fontWeight: "400",
    lineHeight: "20px",
    wordWrap: "break-word",
    marginBottom: "42px",
  },
  formField: {
    borderRadius: "12px",
    width: '396px',
    height: "45px",
    margin: "12px 0",
    "& .MuiOutlinedInput-root": {
      borderRadius: "12px",
    },
    "& .MuiInputLabel-root": {
      color: "#A9A9A9",
    },
    "& .MuiInputLabel-asterisk": {
      color: "#CC0000",
    },
  },
  multilineField: {
    width: '396px',
    height: '117px',
    margin: "12px 0",
    "& .MuiOutlinedInput-root": {
      borderRadius: "12px",
    },
    "& .MuiInputLabel-root": {
      color: "#A9A9A9",
    },
    "& .MuiInputLabel-asterisk": {
      color: "#CC0000",
    },
  },
  fileUploadBox: {
    width: '396px',
    height: "45px",
    margin: "12px 0",
    borderRadius: "12px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    border: "1px rgba(169, 169, 169, 0.73) solid",
    cursor: "pointer",
    color: "#A9A9A9",
    fontSize: "12px",
    fontFamily: "Lexend Deca",
    fontWeight: "400",
  },
  helpText: {
    textAlign: "center",
    color: "#A9A9A9",
    fontSize: '15px',
    fontFamily: "Lexend Deca",
    fontWeight: "400",
    lineHeight: "20px",
    wordWrap: "break-word",
    marginTop: "20px",
  },
  submitButton: {
    marginTop: '20px',
    width: "196px",
    height: "19px%",
    paddingLeft: "173px",
    paddingRight: "173px",
    paddingTop: "13px",
    paddingBottom: "13px",
    background: "#F6F6F6",
    borderRadius: "8px",
    border: "1px #A9A9A9 solid",
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
    display: "inline-flex",
    wordWrap: "break-word",
    textAlign: "center",
    color: "rgba(0, 0, 0, 0.50)",
    fontSize: "15px",
    fontFamily: "Lexend Deca",
    fontWeight: "400",
    lineHeight: "24px",
    "&:hover": {
      background: "#e0e0e0",
    },
  },
};

export default reportToWosomStyles;
