// src/components/AcceptCookiesPopupStyles.ts

import { SxProps, Theme } from '@mui/material';

export const acceptCookiesPopupStyles: { [key: string]: SxProps<Theme> } = {
  dialog: {
    '& .MuiDialog-paper': {
      position: 'absolute',
      bottom: { xl: '6%', sm: '6%' },
      left: { xl: '2%', lg: '3%', sm: '5%' },
      width: { xl: '26%', lg: '31%', md: '38%', xs: '50%' },
      maxWidth: { xl: '395px', md: '433px' },
      padding: { xl: '40px 33px', sm: '25px 25px' },
      boxShadow: 'none',
      margin: '0',
      borderRadius: '12px',
      background: 'white',
      overflowY: 'auto',
      maxHeight: '90vh',
    },
  },
  container: {
    width: '100%',
    height: '100%',
    paddingTop: '41px',
    paddingBottom: '40px',
    paddingLeft: '33px',
    paddingRight: '34px',
    background: 'white',
    borderRadius: '12px',
    justifyContent: 'center',
    alignItems: 'center',
    display: 'inline-flex',
  },
  content: {
    alignSelf: 'stretch',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'center',
    gap: '20px',
    display: 'inline-flex',
  },
  title: {
    textAlign: 'center',
    color: '#111111',
    fontSize: '19px',
    fontFamily: 'Lexend Deca',
    fontWeight: '600',
    lineHeight: '28px',
    wordWrap: 'break-word',
  },
  descriptionContainer: {
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'center',
    display: 'flex',
  },
  description: {
    width: '333px',
    textAlign: 'justify',
    fontSize: '15px',
    fontFamily: 'Lexend Deca',
    fontWeight: '400',
    lineHeight: '30px',
    wordWrap: 'break-word',
    color: '#111111',
    '& a': {
      fontSize: '15px',
      fontFamily: 'Lexend Deca',
      fontWeight: '500',
      color: '#3A61CA',
      textDecoration: 'none',
      '&:hover': {
        textDecoration: 'underline',
      },
    },
  },
  buttonsContainer: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '20px',
    display: 'flex',
    width: '100%', 
  },
  acceptButton: {
    width: '300px',
    justifyContent: 'center',
    alignItems: 'center',
    display: 'inline-flex',
    paddingY:"13px",
    paddingX:"173px",
    whiteSpace: "nowrap",
    height: '50px',
    background: '#F6F6F6',
    borderRadius: '8px',
    border: '1px #A9A9A9 solid',
    fontSize: '15px',
    fontFamily: 'Lexend Deca',
    fontWeight: '400',
    lineHeight: '24px',
    textAlign: 'center',
    color: 'rgba(0, 0, 0, 0.50)',
    '&:hover': {
      background: '#E6E6E6',
      borderColor:'#000',
      borderWidth: 1,
      borderStyle: 'solid',
      color: 'rgba(0, 0, 0, 0.70)',
    },
  },
  declineButton: {
    justifyContent: 'center',
    alignItems: 'center',
    display: 'inline-flex',
    color: '#3A61CA',
    fontSize: '15px',
    fontFamily: 'Lexend Deca',
    fontWeight: '500',
    textDecoration: 'underline',
    lineHeight: '20px',
    wordWrap: 'break-word',
    // '&:hover': {
    //   color: '#2A51AA',
    // },
  },
};
