import { SxProps, Theme } from '@mui/material';

export const categoriesHeroStyles: { [key: string]: SxProps<Theme> } = {
  container: {
    width: '100%',
    height: '100vh',
    position: 'relative',
    background: 'white',
    marginTop: '100px',
    paddingBottom: '150px',
    overflowX: 'hidden',
    overflowY: 'hidden',
  },
  backgroundBox: {
    width: 1280,
    height: 677,
    position: 'absolute',
    top: 101,
    left: 0,
    background: 'rgba(192, 150, 83, 0.20)',
    borderRadius: '8px',
  },
  rotatedText: {
    width: 296,
    position: 'absolute',
    top: 653,
    left: 229,
    transform: 'rotate(-90deg)',
    transformOrigin: '0 0',
    color: '#111111',
    fontSize: 25,
    fontFamily: 'Butterscotch',
    fontWeight: 400,
    textTransform: 'capitalize',
    lineHeight: '86.50px',
    letterSpacing: '1.88px',
    wordWrap: 'break-word',
  },
  mainImage: {
    width: 535,
    height: '676.78px',
    position: 'absolute',
    top: 0,
    left: 633,
    borderRadius: 8,
    border: '1px rgba(169, 169, 169, 0.50) solid',
  },
  headerText: {
    width: 445,
    position: 'absolute',
    top: 267,
    left: 1219,
    color: '#111111',
    fontSize: 25,
    fontFamily: 'Lexend Deca',
    fontWeight: 600,
    textTransform: 'uppercase',
    lineHeight: '40px',
    wordWrap: 'break-word',
  },
  headerTextBox: {
   
    backgroundColor: 'black',
    display: 'flex',
    marginRight: '500px',
    
  },
  secondaryImage: {
    width: 380,
    height: 411,
    position: 'absolute',
    top: 299,
    left: 302,
    background: 'linear-gradient(0deg, #D9D9D9 0%, #D9D9D9 100%)',
    boxShadow: '0px 0px 10px rgba(0, 0, 0, 0.18)',
    borderRadius: 8,
    border: '1px rgba(169, 169, 169, 0.20) solid',
  },
  descriptionText: {
    width: 431,
    position: 'absolute',
    top: 371,
    left: 1219,
    color: '#111111',
    fontSize: 15,
    fontFamily: 'Lexend Deca',
    fontWeight: 400,
    lineHeight: '20px',
    wordWrap: 'break-word',
    marginRight: '250px', // Added space on the right
  },
};
