import { SxProps, Theme } from "@mui/material/styles";

export const fifthSessionStyles: Record<string, SxProps<Theme>> = {
  mainContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    width: "100%",
    padding: "20px 0",
    gap: 2,
    marginTop: "50px",
    marginBottom: "50px",
  },
  container: {
    width: '100%', height: '100%', paddingTop: "50px", paddingBottom: "50px", justifyContent: 'flex-start', alignItems: 'center',  display: 'inline-flex'
  },
  sessionTitle: {
    textAlign: 'center', 
    color: '#111111', 
    fontSize:"25px", 
    fontFamily: 'Lexend Deca', 
    fontWeight: '600', 
    textTransform: 'uppercase', 
    lineHeight: '40px', 
    wordWrap: 'break-word'
  },
  subtitle: {
    fontSize: "15px",
    fontWeight: "400",
    fontFamily: "Lexend Deca",
    textAlign: "center",
    color: "#111111",
    lineHeight: '20px',
  },
  
  card: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "712px",
    maxHeight: "712px",
    width: "316px",
    maxWidth: "316px",
    margin: "auto",
    borderRadius: "8px",
    overflow: "hidden",
    paddingY: '50px',
    boxShadow: "0 8px 16px rgba(0,0,0,0.1)",
    transition: "box-shadow 300ms ease-in-out",
    "&:hover": {
      boxShadow: "0 16px 32px rgba(0,0,0,0.2)",
      "& cardTitle": {
        color: "#111",
      },
    },
  },
  cardContent: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "30px",
    paddingBottom: "30px",
    textAlign: "center",
    width: "100%",
  },
  cardImage: {
    width: '100%', 
    height: '100%', 
    background: 'linear-gradient(0deg, #D9D9D9 0%, #D9D9D9 100%)', 
    borderTopLeftRadius: "8px", 
    borderTopRightRadius: "8px", 
    border: '1px rgba(169, 169, 169, 0.50) solid',
    objectFit: "cover",
  },
  cardTitle: {
    width: '100%', 
    height: '100%', 
    textAlign: 'center', 
    color: '#C09653',
    fontSize: "17px", 
    fontFamily: 'Lexend Deca', 
    fontWeight: '500', 
    lineHeight: "25px", 
    wordWrap: 'break-word'
  },
  cardDescription: {
    width: '100%', 
    height: '100%', 
    textAlign: 'center', 
    color: '#111111', fontSize: "15px", 
    fontFamily: 'Lexend Deca', 
    fontWeight: '400', 
    lineHeight: "20px", 
    wordWrap: 'break-word'
  },
  divider: {
    width: { xs: "50%", sm: "53%", md: "80%" },
    borderBottom: "2px solid #111111",
    marginBottom: "20px",
    marginTop: "20px",
    position: "relative",
    "&::before, &::after": {
      content: '""',
      position: "absolute",
      top: "-4px",
      width: "8px",
      height: "8px",
      borderRadius: "50%",
      backgroundColor: "#111111",
    },
    "&::before": {
      left: "0",
    },
    "&::after": {
      right: "0",
    },
  },
  timeStamp: {
    display: "block",
    textAlign: "center",
    color: "#111111",
    fontSize: 12,
    fontFamily: "Lexend Deca",
    fontWeight: "300",
    marginTop: "5px",
    marginBottom: "5px",
    width: "50%",
    backgroundColor: "#fff",
    marginLeft: "auto",
    marginRight: "auto",
    maxWidth: "200px",
    padding: "8px",
    boxShadow: "0 1px 6px rgba(0,0,0,0.3)",
    position: "relative",
    top: "25px",
    borderRadius: "8px",
  },
  mainBox: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    width: "1278px",
    height: "812px",
    borderRadius: "8px",
    // "& > :first-child": {
    //   marginRight: "30px",
    // },
    // "& > :last-child": {
    //   marginLeft: "30px",
    // },
  },
  getIdeas: {
    textAlign: 'center', 
    color: 'white', 
    fontSize: "15px", 
    fontFamily: 'Lexend Deca', 
    fontWeight: '500', 
    textTransform: 'capitalize', lineHeight: "22.50px", 
    wordWrap: 'break-word',
    backgroundColor: "#C09653",
    paddingX: "20px",
    paddingTop: "10px",
    borderRadius: '12px',
    "&:hover": {
      backgroundColor: "#af8542",
    },
  },
};
