# Use a lightweight Node.js base image
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Set the JAVA_HOME environment variable
ENV JAVA_HOME C:\Users\Kimo\AppData\Local\jdk-11.0.2

# Add Java to the PATH
ENV PATH $PATH:$JAVA_HOME\\bin

# Copy package.json and package-lock.json first for efficient caching
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy the rest of the app files
COPY . .

# Expose the port for the React Native packager
EXPOSE 8081

# Start the React Native packager
CMD ["npm", "start"]
