version: '3'

services:
  react-native:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
      - "19000:19000"
    stdin_open: true
    tty: true
    depends_on:
      - metro-bundler

  metro-bundler:
    image: node:14
    command: npx react-native start --reset-cache
    ports:
      - "8082:8081"
    stdin_open: true
    tty: true
