// src/components/VenueSecondSessionStyles.ts
import { SxProps, Theme } from "@mui/material";

export const venueSecondSessionStyles: { [key: string]: SxProps<Theme> } = {
  container: {
    width: "100%",
    padding: "40px 0",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",

  },
  header: {
    textAlign: "center",
    marginBottom: "20px",
  },
  title: {
    fontSize: "25px",
    fontWeight: 600,
    textTransform: "uppercase",
    lineHeight: "40px",
    marginBottom: "15px",
  },
  subtitle: {
    fontSize: "15px",
    fontWeight: 400,
    lineHeight: "20px",
    marginBottom: "30px",
  },
  filters: {
    gap: "15px",
    marginBottom: "30px",
    justifyContent: "center",
    alignItems: "flex-start",
    display: "inline-flex",
  },
  filterButton: {
    paddingLeft: "25px",
    paddingRight: "25px",
    paddingTop: "5px",
    paddingBottom: "5px",
    background: "rgba(196, 202, 218, 0.29)",
    boxShadow: "0px 4px 10px rgba(0, 0, 0, 0.10)",
    borderRadius: "8px",
    border: "1px #111111 solid",
    justifyContent: "center",
    alignItems: "center",
    gap: "10px",
    display: "flex",
    textAlign: "center",
    color: "#111111",
    fontSize: "14px",
    fontFamily: "Lexend Deca",
    fontWeight: "500px",
    textTransform: "capitalize",
    lineHeight: "24px",
    wordWrap: "break-word",
  },
  venueGrid: {
    width: "1323px",
    paddingBottom: "30px",
  },
  card: {
    width: "312px",
    height: "398px",
    backgroundColor: "white",
    borderRadius: "8px",
    border: "1px rgba(0, 0, 0, 0.3) solid",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    padding: "10px",
  },
  cardMedia: {
    width: "100%",
    height: "100%",
    background: "linear-gradient(0deg, #D9D9D9 0%, #D9D9D9 100%)",
    borderRadius: "8px",
  },
  cardContent: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: "5px",
  },
  cardTitle: {
    textAlign: "center",
    color: "#111111",
    fontSize: "17px",
    fontFamily: "Lexend Deca",
    fontWeight: 500,
    lineHeight: "25px",
  },
  verifiedImage: {
    width: "114px",
    height: "25px",
  },
  ratingContainer: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  proContainer: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
  },
  ratingItem: {
    display: "flex",
    alignItems: "flex-start",
    gap: "5px",
  },
  ratingIcon: {
    width: "20px",
    height: "20px",
    background: "#FFD700",
  },
  capacityIcon: {
    width: "20px",
    height: "15px",
    background: "#111111",
  },
  locationContainer: {
    display: "flex",
    alignItems: "center",
    gap: "5px",
    height: "18px",
  },
  locationIcon: {
    width: "14px",
    height: "20px",
    position: "absolute",
    left: "3px",
    top: "0",
    background: "#111111",
  },
  requestPricing: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    display: "inline-flex",
    paddingTop: "3px",
    paddingBottom: "2px",
    paddingRight: "3px",
    justifyContent: "center",
    whiteSpace: "nowrap",
    wordWrap: "break-word",
    color: "#555454",
    fontSize: "17px",
    fontFamily: "Lexend Deca",
    fontWeight: "300px",
    textTransform: "capitalize",
    lineHeight: "25px",
  },
  footerIcons: {
    display: "flex",
    justifyContent: "flex-start",
    alignItems: "center",
    gap: "8px",
  },
  icon1: {
    width: "23px",
    height: "20.12px",
    background: "#1B84FF",
  },
  icon2: {
    width: "22px",
    height: "18.81px",
    background: "white",
    border: "1px #E00707 solid",
  },
  icon3: {
    width: "16.50px",
    height: "22px",
    background: "#FAD374",
  },
  loadMoreButton: {
    marginTop: "20px",
  },
};
