import { SxProps, Theme } from '@mui/material';

export const venueSessionOneLIStyles: { [key: string]: SxProps<Theme> } = {
  container: {
    width: '100%',
    height: '100%',
    position: 'relative',
    background: 'rgba(192, 150, 83, 0.04)',
    borderTop: '1px #C09653 solid',
    borderBottom: '1px #C09653 solid',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '40px 0',
    marginBottom:"40px",

  },
  header: {
    textAlign: 'center',
    color: '#111111',
    fontSize: 25,
    fontFamily: 'Lexend Deca',
    fontWeight: 600,
    textTransform: 'uppercase',
    lineHeight: '40px',
    marginBottom: '15px',
  },
  subHeader: {
    textAlign: 'center',
    color: '#111111',
    fontSize: 15,
    fontFamily: 'Lexend Deca',
    fontWeight: 400,
    lineHeight: '20px',
    marginBottom: '42px',
  },
  categoriesContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '16px',
    flexWrap: 'wrap',
  },
  category: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '16px',
    textAlign: 'center',
  },
  categoryImage: {
    width: '137px',
    height: '137px',
    boxShadow: '0px 4px 18px rgba(0, 0, 0, 0.15)',
    borderRadius: '50%',
    border: '1px rgba(169, 169, 169, 0.50) solid',
  },
  categoryText: {
    width: '166.30px',
    height: '22px',
    color: '#111111',
    fontSize: 14,
    fontFamily: 'Lexend Deca',
    fontWeight: 600,
    textTransform: 'uppercase',
    lineHeight: '19.98px',
  },
  moreCategoriesButton: {
    padding: '10px 20px',
    background: '#C09653',
    borderRadius: '12px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: 'white',
    fontSize: 15,
    fontFamily: 'Lexend Deca',
    fontWeight: 500,
    textTransform: 'capitalize',
    lineHeight: '22.50px',
    marginTop: '40px',
    '&:hover': {
      background: '#b08445',
    },
  },
  arrow: {
    width: '26px',
    height: '30px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
   
    cursor: 'pointer', // Ensure it shows as clickable
  },
  arrowRight: {
    transform: 'rotate(90deg)',
  },
  arrowIcon: {
    width: '22.51px',
    height: '13.13px',
    background: '#111111',
  },
};
